# Generated by Django 3.0 on 2022-04-19 19:12

from django.db import migrations, models
import django.db.models.deletion
import sistema.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuentas_cobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha_comprado', models.DateField(auto_now=True, verbose_name='Fecha de Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fk_categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistema.Categoria')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('detalles', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imagen', models.ImageField(upload_to=sistema.models.url_producto)),
                ('fk_categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistema.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=140)),
                ('distribuidor', models.ForeignKey(default='nombre', on_delete=django.db.models.deletion.CASCADE, to='sistema.Proveedor')),
                ('producto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistema.Categoria')),
            ],
        ),
    ]
